import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

// Translation resources
const resources = {
  en: {
    translation: {
      // App Title & Status
      appTitle: "Context Subtitles",
      statusConnecting: "Connecting...",
      statusReady: "Ready for captions",
      statusConnectionLost: "Connection lost",

      // Buttons & Actions
      downloadSession: "Download session with captions and pinned words",
      clearSubtitles: "Clear subtitles",
      toggleAccessibility: "Toggle accessibility settings",
      togglePinned: "Toggle pinned words panel",
      toggleDashboard: "Dashboard",

      // Accessibility Panel
      accessibilitySettings: "Accessibility Settings",
      textSize: "Text Size",
      fontFamily: "Font Family",
      lineSpacing: "Line Spacing",
      letterSpacing: "Letter Spacing",
      wordSpacing: "Word Spacing",
      colorOverlay: "Color Overlay",
      highContrastMode: "High Contrast Mode",
      readingGuide: "Reading Guide",
      showSyllables: "Show Syllable Breaks",
      definitionSource: "Definition Source",
      resetDefaults: "Reset to Defaults",

      // Font options
      fontInter: "Inter (Default)",
      fontLexend: "Lexend (Dyslexia-friendly)",
      fontAtkinson: "Atkinson Hyperlegible",
      fontOpenSans: "Open Sans",
      fontComicSans: "Comic Sans MS",

      // Size options
      sizeSmall: "Small",
      sizeMedium: "Medium",
      sizeLarge: "Large",
      sizeExtraLarge: "Extra Large",
      sizeHuge: "Huge",

      // Spacing options
      spacingTight: "Tight",
      spacingNormal: "Normal",
      spacingRelaxed: "Relaxed",
      spacingLoose: "Loose",
      spacingWide: "Wide",
      spacingWider: "Wider",

      // Color overlays
      overlayNone: "None",
      overlayYellow: "Yellow Tint",
      overlayBlue: "Blue Tint",
      overlayGreen: "Green Tint",
      overlayPink: "Pink Tint",

      // Pinned Words
      pinnedWords: "Pinned Words",
      noPinnedWords: "No words pinned yet",
      pinnedWordsHint: "Click the pin button (📍) on any definition to save it here",
      unpinWord: "Remove from pinned words",

      // Clear Modal
      clearSubtitlesTitle: "Clear Subtitles",
      clearChooseOption: "Choose how you want to clear the subtitles:",
      clearDisplayOnly: "Clear Display Only",
      clearDisplayDesc: "Hides subtitles from view, but keeps them in session for download",
      clearEverything: "Clear Everything",
      clearEverythingDesc: "Permanently deletes all subtitles and resets the session",

      // Dashboard (Professor)
      dashboard: "Dashboard",
      wordsLookedUp: "Words Looked Up",
      uniqueWords: "unique words",
      connectedStudents: "Connected Students",
      peak: "Peak",
      totalLookups: "Total Lookups",
      avg: "Avg",
      perStudent: "per student",
      sessionDuration: "Session Duration",
      started: "Started",
      wordsTranscribed: "Words Transcribed",
      liveSubtitles: "Live subtitles",
      recentEngagement: "Recent Engagement",
      mostConfusingTerms: "Most Confusing Terms",
      recentLookups: "Recent Lookups",
      noLookups: "No lookups yet",
      noRecentLookups: "No recent lookups",
      loadingStats: "Loading statistics...",
      lookup: "lookup",
      lookups: "lookups",

      // Time intervals
      last1min: "Last 1 min",
      last5min: "Last 5 min",
      last15min: "Last 15 min",
      last30min: "Last 30 min",

      // Empty states
      waitingForCaptions: "Waiting for live captions to appear...",
      sessionTime: "Session time",
      tipAccessibility: "Tip: Use the ⚙️ button to customize text for better readability",
      tipMobileLongPress: "Long press a word to start selecting multiple words",
      tipMobileTap: "Tap words to add them to your selection, then tap \"Define Selection\"",
      tipDesktopMultiSelect: "Hold Ctrl/Cmd while clicking words to select multiple words like \"artificial intelligence\"",
      tipAIDefinitions: "All definitions are generated by AI for contextual accuracy",
      testGlossary: "Test AI Definitions (Click words for AI-generated explanations)",

      // Definition Popover
      confident: "confident",
      source: "Source",
      pinDefinition: "Pin this definition",
      unpinDefinition: "Unpin this definition",

      // Multi-select
      wordsSelected: "words selected",
      wordSelected: "word selected",
      defineSelection: "Define Selection",
      define: "Define",
      clear: "Clear",

      // Language Selector
      selectLanguage: "Select Language",
      transcriptionLanguage: "Transcription Language",
      uiLanguage: "Interface Language"
    }
  },

  es: {
    translation: {
      // App Title & Status
      appTitle: "Subtítulos Contextuales",
      statusConnecting: "Conectando...",
      statusReady: "Listo para subtítulos",
      statusConnectionLost: "Conexión perdida",

      // Buttons & Actions
      downloadSession: "Descargar sesión con subtítulos y palabras ancladas",
      clearSubtitles: "Borrar subtítulos",
      toggleAccessibility: "Alternar configuración de accesibilidad",
      togglePinned: "Alternar panel de palabras ancladas",
      toggleDashboard: "Panel de Control",

      // Accessibility Panel
      accessibilitySettings: "Configuración de Accesibilidad",
      textSize: "Tamaño del Texto",
      fontFamily: "Familia de Fuente",
      lineSpacing: "Espaciado de Línea",
      letterSpacing: "Espaciado de Letras",
      wordSpacing: "Espaciado de Palabras",
      colorOverlay: "Superposición de Color",
      highContrastMode: "Modo de Alto Contraste",
      readingGuide: "Guía de Lectura",
      showSyllables: "Mostrar Separación de Sílabas",
      definitionSource: "Fuente de Definiciones",
      resetDefaults: "Restablecer Valores Predeterminados",

      // Font options
      fontInter: "Inter (Predeterminada)",
      fontLexend: "Lexend (Amigable para dislexia)",
      fontAtkinson: "Atkinson Hiperlegible",
      fontOpenSans: "Open Sans",
      fontComicSans: "Comic Sans MS",

      // Size options
      sizeSmall: "Pequeño",
      sizeMedium: "Mediano",
      sizeLarge: "Grande",
      sizeExtraLarge: "Extra Grande",
      sizeHuge: "Enorme",

      // Spacing options
      spacingTight: "Ajustado",
      spacingNormal: "Normal",
      spacingRelaxed: "Relajado",
      spacingLoose: "Suelto",
      spacingWide: "Ancho",
      spacingWider: "Más Ancho",

      // Color overlays
      overlayNone: "Ninguno",
      overlayYellow: "Tinte Amarillo",
      overlayBlue: "Tinte Azul",
      overlayGreen: "Tinte Verde",
      overlayPink: "Tinte Rosa",

      // Pinned Words
      pinnedWords: "Palabras Ancladas",
      noPinnedWords: "Aún no hay palabras ancladas",
      pinnedWordsHint: "Haz clic en el botón de anclaje (📍) en cualquier definición para guardarla aquí",
      unpinWord: "Eliminar de palabras ancladas",

      // Clear Modal
      clearSubtitlesTitle: "Borrar Subtítulos",
      clearChooseOption: "Elige cómo quieres borrar los subtítulos:",
      clearDisplayOnly: "Borrar Solo Pantalla",
      clearDisplayDesc: "Oculta los subtítulos de la vista, pero los mantiene en la sesión para descargar",
      clearEverything: "Borrar Todo",
      clearEverythingDesc: "Elimina permanentemente todos los subtítulos y reinicia la sesión",

      // Dashboard (Professor)
      dashboard: "Panel de Control",
      wordsLookedUp: "Palabras Consultadas",
      uniqueWords: "palabras únicas",
      connectedStudents: "Estudiantes Conectados",
      peak: "Pico",
      totalLookups: "Consultas Totales",
      avg: "Promedio",
      perStudent: "por estudiante",
      sessionDuration: "Duración de la Sesión",
      started: "Iniciada",
      wordsTranscribed: "Palabras Transcritas",
      liveSubtitles: "Subtítulos en vivo",
      recentEngagement: "Participación Reciente",
      mostConfusingTerms: "Términos Más Confusos",
      recentLookups: "Consultas Recientes",
      noLookups: "Aún no hay consultas",
      noRecentLookups: "No hay consultas recientes",
      loadingStats: "Cargando estadísticas...",
      lookup: "consulta",
      lookups: "consultas",

      // Time intervals
      last1min: "Último 1 min",
      last5min: "Últimos 5 min",
      last15min: "Últimos 15 min",
      last30min: "Últimos 30 min",

      // Empty states
      waitingForCaptions: "Esperando que aparezcan subtítulos en vivo...",
      sessionTime: "Tiempo de sesión",
      tipAccessibility: "Consejo: Usa el botón ⚙️ para personalizar el texto y mejorar la legibilidad",
      tipMobileLongPress: "Mantén presionada una palabra para comenzar a seleccionar varias palabras",
      tipMobileTap: "Toca palabras para agregarlas a tu selección, luego toca \"Definir Selección\"",
      tipDesktopMultiSelect: "Mantén presionado Ctrl/Cmd mientras haces clic en palabras para seleccionar varias como \"inteligencia artificial\"",
      tipAIDefinitions: "Todas las definiciones son generadas por IA para mayor precisión contextual",
      testGlossary: "Probar Definiciones de IA (Haz clic en palabras para explicaciones generadas por IA)",

      // Definition Popover
      confident: "confianza",
      source: "Fuente",
      pinDefinition: "Anclar esta definición",
      unpinDefinition: "Desanclar esta definición",

      // Multi-select
      wordsSelected: "palabras seleccionadas",
      wordSelected: "palabra seleccionada",
      defineSelection: "Definir Selección",
      define: "Definir",
      clear: "Borrar",

      // Language Selector
      selectLanguage: "Seleccionar Idioma",
      transcriptionLanguage: "Idioma de Transcripción",
      uiLanguage: "Idioma de Interfaz"
    }
  },

  fr: {
    translation: {
      // App Title & Status
      appTitle: "Sous-titres Contextuels",
      statusConnecting: "Connexion...",
      statusReady: "Prêt pour les sous-titres",
      statusConnectionLost: "Connexion perdue",

      // Buttons & Actions
      downloadSession: "Télécharger la session avec sous-titres et mots épinglés",
      clearSubtitles: "Effacer les sous-titres",
      toggleAccessibility: "Basculer les paramètres d'accessibilité",
      togglePinned: "Basculer le panneau des mots épinglés",
      toggleDashboard: "Tableau de Bord",

      // Accessibility Panel
      accessibilitySettings: "Paramètres d'Accessibilité",
      textSize: "Taille du Texte",
      fontFamily: "Famille de Police",
      lineSpacing: "Espacement des Lignes",
      letterSpacing: "Espacement des Lettres",
      wordSpacing: "Espacement des Mots",
      colorOverlay: "Superposition de Couleur",
      highContrastMode: "Mode Contraste Élevé",
      readingGuide: "Guide de Lecture",
      showSyllables: "Afficher la Séparation des Syllabes",
      definitionSource: "Source des Définitions",
      resetDefaults: "Réinitialiser aux Valeurs par Défaut",

      // Dashboard stats
      dashboard: "Tableau de Bord",
      wordsLookedUp: "Mots Consultés",
      connectedStudents: "Étudiants Connectés",
      totalLookups: "Consultations Totales",
      mostConfusingTerms: "Termes les Plus Confus",

      selectLanguage: "Sélectionner la Langue",
      transcriptionLanguage: "Langue de Transcription",
      uiLanguage: "Langue de l'Interface"
    }
  },

  zh: {
    translation: {
      // App Title & Status
      appTitle: "上下文字幕",
      statusConnecting: "连接中...",
      statusReady: "准备好接收字幕",
      statusConnectionLost: "连接丢失",

      downloadSession: "下载带有字幕和固定词的会话",
      clearSubtitles: "清除字幕",
      toggleAccessibility: "切换辅助功能设置",
      toggleDashboard: "仪表板",

      accessibilitySettings: "辅助功能设置",
      textSize: "文本大小",
      fontFamily: "字体系列",
      pinnedWords: "固定的词",
      dashboard: "仪表板",
      wordsLookedUp: "查找的词",
      connectedStudents: "连接的学生",

      selectLanguage: "选择语言",
      transcriptionLanguage: "转录语言",
      uiLanguage: "界面语言"
    }
  },

  hi: {
    translation: {
      appTitle: "संदर्भ उपशीर्षक",
      statusConnecting: "कनेक्ट हो रहा है...",
      statusReady: "उपशीर्षक के लिए तैयार",
      downloadSession: "उपशीर्षक और पिन किए गए शब्दों के साथ सत्र डाउनलोड करें",
      clearSubtitles: "उपशीर्षक साफ़ करें",
      accessibilitySettings: "पहुंच सेटिंग्स",
      textSize: "पाठ का आकार",
      pinnedWords: "पिन किए गए शब्द",
      dashboard: "डैशबोर्ड",
      wordsLookedUp: "देखे गए शब्द",
      connectedStudents: "जुड़े छात्र",
      selectLanguage: "भाषा चुनें",
      transcriptionLanguage: "ट्रांसक्रिप्शन भाषा",
      uiLanguage: "इंटरफ़ेस भाषा"
    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    interpolation: {
      escapeValue: false
    },
    detection: {
      order: ['querystring', 'localStorage', 'navigator'],
      caches: ['localStorage'],
      lookupQuerystring: 'lang'
    }
  });

export default i18n;
